apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  namespace: dev
  labels:
    app: backend
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
        - name: backend
          image: PLACEHOLDER_BACKEND_IMAGE
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_VERSION
              value: "blue"
            - name: ENVIRONMENT
              value: "dev"
